// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjWXFuSFDpEgamWfL_Fs41EM51-sx34UU',
    appId: '1:220080237355:web:927cd84262d84be6b8336e',
    messagingSenderId: '220080237355',
    projectId: 'kp-absensiapp',
    authDomain: 'kp-absensiapp.firebaseapp.com',
    storageBucket: 'kp-absensiapp.firebasestorage.app',
    measurementId: 'G-6F0GF7WG45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJR22Ac-ImTkiS-unPH1OV38WRxZQCWk',
    appId: '1:220080237355:android:ac4f89511b09acf4b8336e',
    messagingSenderId: '220080237355',
    projectId: 'kp-absensiapp',
    storageBucket: 'kp-absensiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvfoALKhh-mZwi0hxy5bw7OhlYuTnrUkI',
    appId: '1:220080237355:ios:882d96dd94dccf44b8336e',
    messagingSenderId: '220080237355',
    projectId: 'kp-absensiapp',
    storageBucket: 'kp-absensiapp.firebasestorage.app',
    iosBundleId: 'com.example.absensiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvfoALKhh-mZwi0hxy5bw7OhlYuTnrUkI',
    appId: '1:220080237355:ios:882d96dd94dccf44b8336e',
    messagingSenderId: '220080237355',
    projectId: 'kp-absensiapp',
    storageBucket: 'kp-absensiapp.firebasestorage.app',
    iosBundleId: 'com.example.absensiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjWXFuSFDpEgamWfL_Fs41EM51-sx34UU',
    appId: '1:220080237355:web:90eb8d94de7bea36b8336e',
    messagingSenderId: '220080237355',
    projectId: 'kp-absensiapp',
    authDomain: 'kp-absensiapp.firebaseapp.com',
    storageBucket: 'kp-absensiapp.firebasestorage.app',
    measurementId: 'G-3VRXHPL66N',
  );
}
